### ISSUE TITLE
Duck-type between result types in the result stream

### ISSUE THREAD

**Issue by renier** [Qiskit-Partners/qiskit-runtime#38]
The result stream is meant to push all kinds of results down to the user. The client should be able, from duck-typing the result object, to differentiate between one and the other and consume what is of interest.

For example, if final results are enabled on the results stream, this would break the vqe and qka programs since they are hard-coded to expect an exact type of result (i.e. interim result) from the stream.

cc: @jyu00 @Cryoris @ismaelfaro

**Comment by jyu00** [comment]
The last missing piece is updating the tutorial, which https://github.com/Qiskit/qiskit-ibm-runtime/issues/174 was open for. Closing this one since the repo is being archived.
