### ISSUE TITLE
VQEProgramResult from runtime job returns NoneType attributes 

### ISSUE THREAD

**Issue by HuangJunye** [Qiskit-Partners/qiskit-runtime#60]
`optimal_parameters`, `optimizer_evals`, `optimizer_history` of VQEProgramResult returned from a runtime job on simulator are `NoneType`.

This leads to errors from cell 18 to 20 in the [VQE runtime tutorial](https://qiskit.org/documentation/partners/qiskit_runtime/tutorials/vqe.html) when plotting optimizer history.

**Comment by HuangJunye** [comment]
I verified that this issue persist for Qiskit 0.28 and 0.29.

**Comment by Cryoris** [comment]
This should've been resolved with #59, since this was a symptom of the same bug 🙂

**Comment by HuangJunye** [comment]
Thanks for fixing this!
