### ISSUE TITLE
 qaoa runtime algorithm: No swap strategy can be found for ibm_perth 

### ISSUE THREAD

**Issue by helenbaumert** [Qiskit-Partners/qiskit-runtime#98]
**Context:**
When using the qaoa runtime algorithm with the 7 qubit quantum device ibm_perth and setting the attribute  'use_swap_strategies':True

**Current bahvior:**  
This currenttly returns an error as No swap strategy can be found for ibm_perth
                    
**Suspected cause**
Please add ibmq_perth and ibmq_lima to listed backend in the get_swap_strategy() function

```
`def get_swap_strategy(
    backend_name: str, n_qubits: Optional[int] = None
) -> Tuple[SwapStrategy, List[int]]:
    Get a swap strategy and the mapping based on the backend.
    Args:
        backend_name: the name of the backend as a string.
        n_qubits: the number of qubits to use. If not specified then all qubits will be used.
    Returns:
        A tuple where the first element is a swap strategy for the given backend and the second
        element is the list of physical qubits that the swap strategy applies to.
 

    if backend_name in [
        "ibmq_belem",
        "ibmq_quito",
        "ibmq_lime",  ## shouldn't it be ibmq_lima 
        "fake_belem",
        "fake_quito",
        "fake_lime",
    ]:
        return FiveQubitTeeSwapStrategy(), list(range(5))

    if backend_name in [
        "fake_lagos",
        "ibm_lagos",
        "ibmq_casablanca",
        "ibm_nairobi",
        "ibmq_jakarta", #please add ibm_perth   (without q)
    ]:
        return SevenQubitHeavySwapStrategy(n_qubits), list(range(n_qubits))`
```
Further suggestion for enhancements:
- if a simulator is selected ignore the swap strategy parameter or continue with alternative behavior (optimization level) if no swap strategy can be found.

**Comment by jyu00** [comment]
This has been fixed. 

Also this repo is being archived. Please open any future issues in https://github.com/Qiskit/qiskit-ibm-runtime/issues
